Fix/master to release 02122022
prefeiturasp/SME-NovoSGP-WebClient pull request #1729
Opened 2022-12-02 15:55 UTC by robsonamcom

2022-12-02 16:06 UTC, GabrielVedolin approved these changes

2022-12-02 16:07 UTC, cleitondutra requested changes

2022-12-02 16:07 UTC, cleitondutra commented on src/SME.SGP.WebClient/src/componentes-sgp/QuestionarioDinamico/Componentes/campoDinamicoPeriodoEscolar.js
> +      const anoVersao = versaoPlano? new Date(versaoPlano.criadoEm).getFullYear() : null ;
Aqui tem uma regra de negócio do Plano em um componente genérico

2022-12-02 16:34 UTC, robsonamcom commented on src/SME.SGP.WebClient/src/componentes-sgp/QuestionarioDinamico/Componentes/campoDinamicoPeriodoEscolar.js
> +      const anoVersao = versaoPlano? new Date(versaoPlano.criadoEm).getFullYear() : null ;
Cleiton, esse PR é de uma descida de master para release. Você consegue ajustar?

2022-12-02 18:41 UTC, cleitondutra commented on src/SME.SGP.WebClient/src/componentes-sgp/QuestionarioDinamico/Componentes/campoDinamicoPeriodoEscolar.js
> +      const anoVersao = versaoPlano? new Date(versaoPlano.criadoEm).getFullYear() : null ;
Eu gostaria de ajustar sim mas o teste do bug teria que ser realizado novamente e enviado para r2 e master antes de descer para release.
Caso não seja possível fazer esse fluxo vamos aprovar mas precisamos ver um tempo para ajustar isso junto com o Gui ou o Gabriel em alguma outra atividade.

2022-12-08 21:05 UTC, cleitondutra approved these changes

2022-12-08 21:05 UTC, merged