Fix/42796
prefeiturasp/SME-NovoSGP-WebClient pull request #441
Opened 2021-08-31 21:57 UTC by BernardRibeiro

AB#42796

Adicionado spinner desabilitando botões de ação após salvar.

2021-09-03 23:32 UTC, cleitondutra-amcom requested changes
@BernardRibeiro  Tem alguns comentários e tem conflitos para ajustar ;)

2021-09-03 23:32 UTC, cleitondutra-amcom commented on src/SME.SGP.WebClient/src/paginas/Relatorios/DiarioClasse/BoletimSimples/componentes/Filtro/index.js
> +  async function CarregarModalidades(){
O C é minúsculo e pode ser uma arrow function

2021-09-03 23:32 UTC, cleitondutra-amcom commented on src/SME.SGP.WebClient/src/paginas/Fechamento/ConselhoClasse/DadosConselhoClasse/ListasNotasConceito/listasNotasConceitos.js
> +          if (
@BernardRibeiro neste caso então pode ser uma string vazia não deve entrar no if?

2021-09-03 23:32 UTC, cleitondutra-amcom commented on src/SME.SGP.WebClient/src/paginas/DiarioClasse/AulaDadaAulaPrevista/aulaDadaAulaPrevista.js
> +      ) : null}{' '}
```suggestion
      ) : null}
```

2021-09-03 23:32 UTC, cleitondutra-amcom commented on src/SME.SGP.WebClient/src/paginas/DiarioClasse/AulaDadaAulaPrevista/aulaDadaAulaPrevista.js
> +    <Loader loading={carregamento} tip="Carregando...">
```suggestion
    <Loader loading={carregamento}>
```

2021-09-03 23:32 UTC, cleitondutra-amcom commented on src/SME.SGP.WebClient/src/paginas/DiarioClasse/AulaDadaAulaPrevista/aulaDadaAulaPrevista.js
> +    <Loader loading={carregamento} tip="Carregando...">
Dentro do componente loader já tem uma defaultProps com o valor   tip: 'Carregando...',

2021-09-10 19:41 UTC, BernardRibeiro commented on src/SME.SGP.WebClient/src/paginas/Relatorios/DiarioClasse/BoletimSimples/componentes/Filtro/index.js
> +  async function CarregarModalidades(){
Ok

2021-09-10 19:41 UTC, BernardRibeiro commented on src/SME.SGP.WebClient/src/paginas/DiarioClasse/AulaDadaAulaPrevista/aulaDadaAulaPrevista.js
> +      ) : null}{' '}
Retirado

2021-09-10 19:41 UTC, BernardRibeiro commented on src/SME.SGP.WebClient/src/paginas/DiarioClasse/AulaDadaAulaPrevista/aulaDadaAulaPrevista.js
> +    <Loader loading={carregamento} tip="Carregando...">
Perfeito! Não tinha notado essa.

2021-09-10 19:47 UTC, BernardRibeiro commented on src/SME.SGP.WebClient/src/paginas/Fechamento/ConselhoClasse/DadosConselhoClasse/ListasNotasConceito/listasNotasConceitos.js
> +          if (
Então, pelo backend sempre retornará null ou algum valor para nota. Mas vejo que o ideal seria prever qualquer tipo inválido.

2021-09-10 19:59 UTC, BernardRibeiro commented on src/SME.SGP.WebClient/src/paginas/Fechamento/ConselhoClasse/DadosConselhoClasse/ListasNotasConceito/listasNotasConceitos.js
> +          if (
Feito! Utilizei a função valorNuloOuVazio conforme tua sugestão

2021-09-10 20:01 UTC, cleitondutra-amcom approved these changes

2021-09-10 20:01 UTC, merged